# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
broadcast = 'packages/contracts/broadcast'
cache_path = 'packages/contracts/cache'
libs = ['packages/contracts/lib']
out = 'packages/contracts/out'
script = 'packages/contracts/script'
src = 'packages/contracts/src'
test = 'packages/contracts/test'
solc_version = "0.8.19"

[fmt]
line_length = 100
